In [87]:
import pandas as pd
import numpy as np

In [88]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [89]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [90]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [91]:
movies.shape

(4803, 20)

In [92]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [93]:
movies = movies.merge(credits, on='title')

In [94]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [95]:
movies['original_language'].value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: count, dtype: int64

In [96]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [97]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [98]:

movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [99]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [100]:
movies.dropna()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [101]:
movies.dropna(inplace=True)

In [102]:
movies.duplicated().sum()

np.int64(0)

In [103]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [104]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#['Action','Adventure','Fantasy','Science Fiction']

In [105]:
"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}]"

"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}]"

In [106]:
import ast

In [107]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [108]:

movies['genres'] = movies['genres'].apply(convert)

In [109]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [110]:
movies['keywords'] = movies['keywords'].apply(convert)

In [111]:
import ast

def convert3(obj):
    L = []
    counter = 0
    
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
            
    return L

In [112]:
movies['cast'].apply(convert3)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [113]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [114]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [115]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [116]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [117]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]

In [118]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [119]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [120]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]

In [121]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [122]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...",[AndrewStanton]

In [123]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [124]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [125]:
new_df = movies[['movie_id','title','tags']]

In [126]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\DELL\AppData\Local\Temp\ipykernel_12424\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [127]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [128]:
import nltk

In [129]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [130]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [131]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\DELL\AppData\Local\Temp\ipykernel_12424\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [132]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d [ { " c a s t _ i d " : 2 4 2 , " c h a r a c t e r " : " j a k e s u l l y " , " c r e d i t _ i d " : " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " , " g e n d e r " : 2 , " i d " : 6 5 7 3 1 , " n a m e " : " s a m w o r t h i n g t o n " , " o r d e r " : 0 } , { " c a s t _ i d " : 3 , " c h a r a c t e r " : " n e y t i r i " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " , " g e n d e r " : 1 , " i d " : 8 6 9 1 , " n a m e " : " z o e s a l d a n a " , " o r d e r " : 1 } , { " c a s t _ i d " : 2 5 , " c h a r a c t e r " : " d r . g r a c e a u g u s t i n e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " , " g e n d e r " : 1 , " i d " : 1 0 2 0 5 , " n a m e " : " s i g o u r n e y w e a v e r " , " o r d e r " : 2 } , { " c a s t _ i d " : 4 , " c h a r a c t e r " : " c o l . q u a r i t c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " , " g e n d e r " : 2 , " i d " : 3 2 7 4 7 , " n a m e " : " s t e p h e n l a n g " , " o r d e r " : 3 } , { " c a s t _ i d " : 5 , " c h a r a c t e r " : " t r u d y c h a c o n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " , " g e n d e r " : 1 , " i d " : 1 7 6 4 7 , " n a m e " : " m i c h e l l e r o d r i g u e z " , " o r d e r " : 4 } , { " c a s t _ i d " : 8 , " c h a r a c t e r " : " s e l f r i d g e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " , " g e n d e r " : 2 , " i d " : 1 7 7 1 , " n a m e " : " g i o v a n n i r i b i s i " , " o r d e r " : 5 } , { " c a s t _ i d " : 7 , " c h a r a c t e r " : " n o r m s p e l l m a n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " , " g e n d e r " : 2 , " i d " : 5 9 2 3 1 , " n a m e " : " j o e l d a v i d m o o r e " , " o r d e r " : 6 } , { " c a s t _ i d " : 9 , " c h a r a c t e r " : " m o a t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " , " g e n d e r " : 1 , " i d " : 3 0 4 8 5 , " n a m e " : " c c h p o u n d e r " , " o r d e r " : 7 } , { " c a s t _ i d " : 1 1 , " c h a r a c t e r " : " e y t u k a n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " , " g e n d e r " : 2 , " i d " : 1 5 8 5 3 , " n a m e " : " w e s s t u d i " , " o r d e r " : 8 } , { " c a s t _ i d " : 1 0 , " c h a r a c t e r " : " t s u \' t e y " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " , " g e n d e r " : 2 , " i d " : 1 0 9 6 4 , " n a m e " : " l a z a l o n s o " , " o r d e r " : 9 } , { " c a s t _ i d " : 1 2 , " c h a r a c t e r " : " d r . m a x p a t e l " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " , " g e n d e r " : 2 , " i d " : 9 5 6 9 7 , " n a m e " : " d i l e e p r a o " , " o r d e r " : 1 0 } , { " c a s t _ i d " : 1 3 , " c h a r a c t e r " : " l y l e w a i n f l e e t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " , " g e n d e r " : 2 , " i d " : 9 8 2 1 5 , " n a m e " : " m a t t g e r a l d " , " o r d e r " : 1 1 } , { " c a s t _ i d " : 3 2 , " c h a r a c t e r " : " p r i v a t e f i k e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " , " g e n d e r " : 2 , " i d " : 1 5 4 1 5 3 , " n a m e " : " s e a n a n t h o n y m o r a n " , " o r d e r " : 1 2 } , { " c a s t _ i d " : 3 3 , " c h a r a c t e r " : " c r y o v a u l t m e d t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " , " g e n d e r " : 2 , " i d " : 3 9 7 3 1 2 , " n a m e " : " j a s o n w h y t e " , " o r d e r " : 1 3 } , { " c a s t _ i d " : 3 4 , " c h a r a c t e r " : " v e n t u r e s t a r c r e w c h i e f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " , " g e n d e r " : 2 , " i d " : 4 2 3 1 7 , " n a m e " : " s c o t t l a w r e n c e " , " o r d e r " : 1 4 } , { " c a s t _ i d " : 3 5 , " c h a r a c t e r " : " l o c k u p t r o o p e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " , " g e n d e r " : 2 , " i d " : 9 8 6 7 3 4 , " n a m e " : " k e l l y k i l g o u r " , " o r d e r " : 1 5 } , { " c a s t _ i d " : 3 6 , " c h a r a c t e r " : " s h u t t l e p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 2 7 , " n a m e " : " j a m e s p a t r i c k p i t t " , " o r d e r " : 1 6 } , { " c a s t _ i d " : 3 7 , " c h a r a c t e r " : " s h u t t l e c o - p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " , " g e n d e r " : 0 , " i d " : 1 1 8 0 9 3 6 , " n a m e " : " s e a n p a t r i c k m u r p h y " , " o r d e r " : 1 7 } , { " c a s t _ i d " : 3 8 , " c h a r a c t e r " : " s h u t t l e c r e w c h i e f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " , " g e n d e r " : 2 , " i d " : 1 0 1 9 5 7 8 , " n a m e " : " p e t e r d i l l o n " , " o r d e r " : 1 8 } , { " c a s t _ i d " : 3 9 , " c h a r a c t e r " : " t r a c t o r o p e r a t o r / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " , " g e n d e r " : 0 , " i d " : 9 1 4 4 3 , " n a m e " : " k e v i n d o r m a n " , " o r d e r " : 1 9 } , { " c a s t _ i d " : 4 0 , " c h a r a c t e r " : " d r a g o n g u n s h i p p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " , " g e n d e r " : 2 , " i d " : 1 7 3 3 9 1 , " n a m e " : " k e l s o n h e n d e r s o n " , " o r d e r " : 2 0 } , { " c a s t _ i d " : 4 1 , " c h a r a c t e r " : " d r a g o n g u n s h i p g u n n e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 3 6 , " n a m e " : " d a v i d v a n h o r n " , " o r d e r " : 2 1 } , { " c a s t _ i d " : 4 2 , " c h a r a c t e r " : " d r a g o n g u n s h i p n a v i g a t o r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " , " g e n d e r " : 0 , " i d " : 2 1 5 9 1 3 , " n a m e " : " j a c o b t o m u r i " , " o r d e r " : 2 2 } , { " c a s t _ i d " : 4 3 , " c h a r a c t e r " : " s u i t # 1 " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " , " g e n d e r " : 0 , " i d " : 1 4 3 2 0 6 , " n a m e " : " m i c h a e l b l a i n - r o z g a y " , " o r d e r " : 2 3 } , { " c a s t _ i d " : 4 4 , " c h a r a c t e r " : " s u i t # 2 " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " , " g e n d e r " : 2 , " i d " : 1 6 9 6 7 6 , " n a m e " : " j o n c u r r y " , " o r d e r " : 2 4 } , { " c a s t _ i d " : 4 6 , " c h a r a c t e r " : " a m b i e n t r o o m t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " , " g e n d e r " : 0 , " i d " : 1 0 4 8 6 1 0 , " n a m e " : " l u k e h a w k e r " , " o r d e r " : 2 5 } , { " c a s t _ i d " : 4 7 , " c h a r a c t e r " : " a m b i e n t r o o m t e c h / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " , " g e n d e r " : 0 , " i d " : 4 2 2 8 8 , " n a m e " : " w o o d y s c h u l t z " , " o r d e r " : 2 6 } , { " c a s t _ i d " : 4 8 , " c h a r a c t e r " : " h o r s e c l a n l e a d e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " , " g e n d e r " : 2 , " i d " : 6 8 2 7 8 , " n a m e " : " p e t e r m e n s a h " , " o r d e r " : 2 7 } , { " c a s t _ i d " : 4 9 , " c h a r a c t e r " : " l i n k r o o m t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 4 7 , " n a m e " : " s o n i a y e e " , " o r d e r " : 2 8 } , { " c a s t _ i d " : 5 0 , " c h a r a c t e r " : " b a s k e t b a l l a v a t a r / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " , " g e n d e r " : 1 , " i d " : 1 2 0 7 2 4 8 , " n a m e " : " j a h n e l c u r f m a n " , " o r d e r " : 2 9 } , { " c a s t _ i d " : 5 1 , " c h a r a c t e r " : " b a s k e t b a l l a v a t a r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " , " g e n d e r " : 0 , " i d " : 8 9 7 1 4 , " n a m e " : " i l r a m c h o i " , " o r d e r " : 3 0 } , { " c a s t _ i d " : 5 2 , " c h a r a c t e r " : " n a \' v i c h i l d " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 4 9 , " n a m e " : " k y l a w a r r e n " , " o r d e r " : 3 1 } , { " c a s t _ i d " : 5 3 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 0 , " n a m e " : " l i s a r o u m a i n " , " o r d e r " : 3 2 } , { " c a s t _ i d " : 5 4 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " , " g e n d e r " : 1 , " i d " : 8 3 1 0 5 , " n a m e " : " d e b r a w i l s o n " , " o r d e r " : 3 3 } , { " c a s t _ i d " : 5 7 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 3 , " n a m e " : " c h r i s m a l a " , " o r d e r " : 3 4 } , { " c a s t _ i d " : 5 5 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 1 , " n a m e " : " t a y l o r k i b b y " , " o r d e r " : 3 5 } , { " c a s t _ i d " : 5 6 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 2 , " n a m e " : " j o d i e l a n d a u " , " o r d e r " : 3 6 } , { " c a s t _ i d " : 5 8 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 4 , " n a m e " : " j u l i e l a m m " , " o r d e r " : 3 7 } , { " c a s t _ i d " : 5 9 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 7 , " n a m e " : " c u l l e n b . m a d d e n " , " o r d e r " : 3 8 } , { " c a s t _ i d " : 6 0 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 9 , " n a m e " : " j o s e p h b r a d y m a d d e n " , " o r d e r " : 3 9 } , { " c a s t _ i d " : 6 1 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 2 , " n a m e " : " f r a n k i e t o r r e s " , " o r d e r " : 4 0 } , { " c a s t _ i d " : 6 2 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " , " g e n d e r " : 1 , " i d " : 1 1 5 8 6 0 0 , " n a m e " : " a u s t i n w i l s o n " , " o r d e r " : 4 1 } , { " c a s t _ i d " : 6 3 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " , " g e n d e r " : 1 , " i d " : 9 8 3 7 0 5 , " n a m e " : " s a r a w i l s o n " , " o r d e r " : 4 2 } , { " c a s t _ i d " : 6 4 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 3 , " n a m e " : " t a m i c a w a s h i n g t o n - m i l l e r " , " o r d e r " : 4 3 } , { " c a s t _ i d " : 6 5 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " , " g e n d e r " : 1 , " i d " : 1 1 4 5 0 9 8 , " n a m e " : " l u c y b r i a n t " , " o r d e r " : 4 4 } , { " c a s t _ i d " : 6 6 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " , " g e n d e r " : 2 , " i d " : 3 3 3 0 5 , " n a m e " : " n a t h a n m e i s t e r " , " o r d e r " : 4 5 } , { " c a s t _ i d " : 6 7 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 4 , " n a m e " : " g e r r y b l a i r " , " o r d e r " : 4 6 } , { " c a s t _ i d " : 6 8 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " , " g e n d e r " : 2 , " i d " : 3 3 3 1 1 , " n a m e " : " m a t t h e w c h a m b e r l a i n " , " o r d e r " : 4 7 } , { " c a s t _ i d " : 6 9 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 5 , " n a m e " : " p a u l y a t e s " , " o r d e r " : 4 8 } , { " c a s t _ i d " : 7 0 , " c h a r a c t e r " : " o p c e n t e r d u t y o f f i c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 6 , " n a m e " : " w r a y w i l s o n " , " o r d e r " : 4 9 } , { " c a s t _ i d " : 7 1 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " , " g e n d e r " : 2 , " i d " : 5 4 4 9 2 , " n a m e " : " j a m e s g a y l y n " , " o r d e r " : 5 0 } , { " c a s t _ i d " : 7 2 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 7 , " n a m e " : " m e l v i n l e n o c l a r k i i i " , " o r d e r " : 5 1 } , { " c a s t _ i d " : 7 3 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 8 , " n a m e " : " c a r v o n f u t r e l l " , " o r d e r " : 5 2 } , { " c a s t _ i d " : 7 4 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 9 , " n a m e " : " b r a n d o n j e l k e s " , " o r d e r " : 5 3 } , { " c a s t _ i d " : 7 5 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 0 , " n a m e " : " m i c a h m o c h " , " o r d e r " : 5 4 } , { " c a s t _ i d " : 7 6 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 1 , " n a m e " : " h a n n i y a h m u h a m m a d " , " o r d e r " : 5 5 } , { " c a s t _ i d " : 7 7 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 2 , " n a m e " : " c h r i s t o p h e r n o l e n " , " o r d e r " : 5 6 } , { " c a s t _ i d " : 7 8 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 3 , " n a m e " : " c h r i s t a o l i v e r " , " o r d e r " : 5 7 } , { " c a s t _ i d " : 7 9 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 4 , " n a m e " : " a p r i l m a r i e t h o m a s " , " o r d e r " : 5 8 } , { " c a s t _ i d " : 8 0 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 5 , " n a m e " : " b r a v i t a a . t h r e a t t " , " o r d e r " : 5 9 } , { " c a s t _ i d " : 8 1 , " c h a r a c t e r " : " m i n i n g c h i e f ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 6 , " n a m e " : " c o l i n b l e a s d a l e " , " o r d e r " : 6 0 } , { " c a s t _ i d " : 8 2 , " c h a r a c t e r " : " v e t e r a n m i n e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " , " g e n d e r " : 0 , " i d " : 1 0 7 9 6 9 , " n a m e " : " m i k e b o d n a r " , " o r d e r " : 6 1 } , { " c a s t _ i d " : 8 3 , " c h a r a c t e r " : " r i c h a r d ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 8 , " n a m e " : " m a t t c l a y t o n " , " o r d e r " : 6 2 } , { " c a s t _ i d " : 8 4 , " c h a r a c t e r " : " n a v \' i ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 7 " , " g e n d e r " : 1 , " i d " : 1 4 7 8 9 8 , " n a m e " : " n i c o l e d i o n n e " , " o r d e r " : 6 3 } , { " c a s t _ i d " : 8 5 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 0 , " n a m e " : " j a m i e h a r r i s o n " , " o r d e r " : 6 4 } , { " c a s t _ i d " : 8 6 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 1 , " n a m e " : " a l l a n h e n r y " , " o r d e r " : 6 5 } , { " c a s t _ i d " : 8 7 , " c h a r a c t e r " : " g r o u n d t e c h n i c i a n ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 3 " , " g e n d e r " : 2 , " i d " : 1 2 0 7 2 8 2 , " n a m e " : " a n t h o n y i n g r u b e r " , " o r d e r " : 6 6 } , { " c a s t _ i d " : 8 8 , " c h a r a c t e r " : " f l i g h t c r e w m e c h a n i c ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 3 , " n a m e " : " a s h l e y j e f f e r y " , " o r d e r " : 6 7 } , { " c a s t _ i d " : 1 4 , " c h a r a c t e r " : " s a m s o n p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 9 " , " g e n d e r " : 0 , " i d " : 9 8 2 1 6 , " n a m e " : " d e a n k n o w s l e y " , " o r d e r " : 6 8 } , { " c a s t _ i d " : 8 9 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 b " , " g e n d e r " : 0 , " i d " : 1 2 0 1 3 9 9 , " n a m e " : " j o s e p h m i k a - h u n t " , " o r d e r " : 6 9 } , { " c a s t _ i d " : 9 0 , " c h a r a c t e r " : " b a n s h e e ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 f " , " g e n d e r " : 0 , " i d " : 2 3 6 6 9 6 , " n a m e " : " t e r r y n o t a r y " , " o r d e r " : 7 0 } , { " c a s t _ i d " : 9 1 , " c h a r a c t e r " : " s 

In [133]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

C:\Users\DELL\AppData\Local\Temp\ipykernel_12424\1380776331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [134]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [135]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d [ { " c a s t _ i d " : 2 4 2 , " c h a r a c t e r " : " j a k e s u l l y " , " c r e d i t _ i d " : " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " , " g e n d e r " : 2 , " i d " : 6 5 7 3 1 , " n a m e " : " s a m w o r t h i n g t o n " , " o r d e r " : 0 } , { " c a s t _ i d " : 3 , " c h a r a c t e r " : " n e y t i r i " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " , " g e n d e r " : 1 , " i d " : 8 6 9 1 , " n a m e " : " z o e s a l d a n a " , " o r d e r " : 1 } , { " c a s t _ i d " : 2 5 , " c h a r a c t e r " : " d r . g r a c e a u g u s t i n e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " , " g e n d e r " : 1 , " i d " : 1 0 2 0 5 , " n a m e " : " s i g o u r n e y w e a v e r " , " o r d e r " : 2 } , { " c a s t _ i d " : 4 , " c h a r a c t e r " : " c o l . q u a r i t c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " , " g e n d e r " : 2 , " i d " : 3 2 7 4 7 , " n a m e " : " s t e p h e n l a n g " , " o r d e r " : 3 } , { " c a s t _ i d " : 5 , " c h a r a c t e r " : " t r u d y c h a c o n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " , " g e n d e r " : 1 , " i d " : 1 7 6 4 7 , " n a m e " : " m i c h e l l e r o d r i g u e z " , " o r d e r " : 4 } , { " c a s t _ i d " : 8 , " c h a r a c t e r " : " s e l f r i d g e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " , " g e n d e r " : 2 , " i d " : 1 7 7 1 , " n a m e " : " g i o v a n n i r i b i s i " , " o r d e r " : 5 } , { " c a s t _ i d " : 7 , " c h a r a c t e r " : " n o r m s p e l l m a n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " , " g e n d e r " : 2 , " i d " : 5 9 2 3 1 , " n a m e " : " j o e l d a v i d m o o r e " , " o r d e r " : 6 } , { " c a s t _ i d " : 9 , " c h a r a c t e r " : " m o a t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " , " g e n d e r " : 1 , " i d " : 3 0 4 8 5 , " n a m e " : " c c h p o u n d e r " , " o r d e r " : 7 } , { " c a s t _ i d " : 1 1 , " c h a r a c t e r " : " e y t u k a n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " , " g e n d e r " : 2 , " i d " : 1 5 8 5 3 , " n a m e " : " w e s s t u d i " , " o r d e r " : 8 } , { " c a s t _ i d " : 1 0 , " c h a r a c t e r " : " t s u \' t e y " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " , " g e n d e r " : 2 , " i d " : 1 0 9 6 4 , " n a m e " : " l a z a l o n s o " , " o r d e r " : 9 } , { " c a s t _ i d " : 1 2 , " c h a r a c t e r " : " d r . m a x p a t e l " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " , " g e n d e r " : 2 , " i d " : 9 5 6 9 7 , " n a m e " : " d i l e e p r a o " , " o r d e r " : 1 0 } , { " c a s t _ i d " : 1 3 , " c h a r a c t e r " : " l y l e w a i n f l e e t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " , " g e n d e r " : 2 , " i d " : 9 8 2 1 5 , " n a m e " : " m a t t g e r a l d " , " o r d e r " : 1 1 } , { " c a s t _ i d " : 3 2 , " c h a r a c t e r " : " p r i v a t e f i k e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " , " g e n d e r " : 2 , " i d " : 1 5 4 1 5 3 , " n a m e " : " s e a n a n t h o n y m o r a n " , " o r d e r " : 1 2 } , { " c a s t _ i d " : 3 3 , " c h a r a c t e r " : " c r y o v a u l t m e d t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " , " g e n d e r " : 2 , " i d " : 3 9 7 3 1 2 , " n a m e " : " j a s o n w h y t e " , " o r d e r " : 1 3 } , { " c a s t _ i d " : 3 4 , " c h a r a c t e r " : " v e n t u r e s t a r c r e w c h i e f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " , " g e n d e r " : 2 , " i d " : 4 2 3 1 7 , " n a m e " : " s c o t t l a w r e n c e " , " o r d e r " : 1 4 } , { " c a s t _ i d " : 3 5 , " c h a r a c t e r " : " l o c k u p t r o o p e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " , " g e n d e r " : 2 , " i d " : 9 8 6 7 3 4 , " n a m e " : " k e l l y k i l g o u r " , " o r d e r " : 1 5 } , { " c a s t _ i d " : 3 6 , " c h a r a c t e r " : " s h u t t l e p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 2 7 , " n a m e " : " j a m e s p a t r i c k p i t t " , " o r d e r " : 1 6 } , { " c a s t _ i d " : 3 7 , " c h a r a c t e r " : " s h u t t l e c o - p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " , " g e n d e r " : 0 , " i d " : 1 1 8 0 9 3 6 , " n a m e " : " s e a n p a t r i c k m u r p h y " , " o r d e r " : 1 7 } , { " c a s t _ i d " : 3 8 , " c h a r a c t e r " : " s h u t t l e c r e w c h i e f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " , " g e n d e r " : 2 , " i d " : 1 0 1 9 5 7 8 , " n a m e " : " p e t e r d i l l o n " , " o r d e r " : 1 8 } , { " c a s t _ i d " : 3 9 , " c h a r a c t e r " : " t r a c t o r o p e r a t o r / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " , " g e n d e r " : 0 , " i d " : 9 1 4 4 3 , " n a m e " : " k e v i n d o r m a n " , " o r d e r " : 1 9 } , { " c a s t _ i d " : 4 0 , " c h a r a c t e r " : " d r a g o n g u n s h i p p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " , " g e n d e r " : 2 , " i d " : 1 7 3 3 9 1 , " n a m e " : " k e l s o n h e n d e r s o n " , " o r d e r " : 2 0 } , { " c a s t _ i d " : 4 1 , " c h a r a c t e r " : " d r a g o n g u n s h i p g u n n e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 3 6 , " n a m e " : " d a v i d v a n h o r n " , " o r d e r " : 2 1 } , { " c a s t _ i d " : 4 2 , " c h a r a c t e r " : " d r a g o n g u n s h i p n a v i g a t o r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " , " g e n d e r " : 0 , " i d " : 2 1 5 9 1 3 , " n a m e " : " j a c o b t o m u r i " , " o r d e r " : 2 2 } , { " c a s t _ i d " : 4 3 , " c h a r a c t e r " : " s u i t # 1 " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " , " g e n d e r " : 0 , " i d " : 1 4 3 2 0 6 , " n a m e " : " m i c h a e l b l a i n - r o z g a y " , " o r d e r " : 2 3 } , { " c a s t _ i d " : 4 4 , " c h a r a c t e r " : " s u i t # 2 " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " , " g e n d e r " : 2 , " i d " : 1 6 9 6 7 6 , " n a m e " : " j o n c u r r y " , " o r d e r " : 2 4 } , { " c a s t _ i d " : 4 6 , " c h a r a c t e r " : " a m b i e n t r o o m t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " , " g e n d e r " : 0 , " i d " : 1 0 4 8 6 1 0 , " n a m e " : " l u k e h a w k e r " , " o r d e r " : 2 5 } , { " c a s t _ i d " : 4 7 , " c h a r a c t e r " : " a m b i e n t r o o m t e c h / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " , " g e n d e r " : 0 , " i d " : 4 2 2 8 8 , " n a m e " : " w o o d y s c h u l t z " , " o r d e r " : 2 6 } , { " c a s t _ i d " : 4 8 , " c h a r a c t e r " : " h o r s e c l a n l e a d e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " , " g e n d e r " : 2 , " i d " : 6 8 2 7 8 , " n a m e " : " p e t e r m e n s a h " , " o r d e r " : 2 7 } , { " c a s t _ i d " : 4 9 , " c h a r a c t e r " : " l i n k r o o m t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 4 7 , " n a m e " : " s o n i a y e e " , " o r d e r " : 2 8 } , { " c a s t _ i d " : 5 0 , " c h a r a c t e r " : " b a s k e t b a l l a v a t a r / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " , " g e n d e r " : 1 , " i d " : 1 2 0 7 2 4 8 , " n a m e " : " j a h n e l c u r f m a n " , " o r d e r " : 2 9 } , { " c a s t _ i d " : 5 1 , " c h a r a c t e r " : " b a s k e t b a l l a v a t a r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " , " g e n d e r " : 0 , " i d " : 8 9 7 1 4 , " n a m e " : " i l r a m c h o i " , " o r d e r " : 3 0 } , { " c a s t _ i d " : 5 2 , " c h a r a c t e r " : " n a \' v i c h i l d " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 4 9 , " n a m e " : " k y l a w a r r e n " , " o r d e r " : 3 1 } , { " c a s t _ i d " : 5 3 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 0 , " n a m e " : " l i s a r o u m a i n " , " o r d e r " : 3 2 } , { " c a s t _ i d " : 5 4 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " , " g e n d e r " : 1 , " i d " : 8 3 1 0 5 , " n a m e " : " d e b r a w i l s o n " , " o r d e r " : 3 3 } , { " c a s t _ i d " : 5 7 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 3 , " n a m e " : " c h r i s m a l a " , " o r d e r " : 3 4 } , { " c a s t _ i d " : 5 5 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 1 , " n a m e " : " t a y l o r k i b b y " , " o r d e r " : 3 5 } , { " c a s t _ i d " : 5 6 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 2 , " n a m e " : " j o d i e l a n d a u " , " o r d e r " : 3 6 } , { " c a s t _ i d " : 5 8 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 4 , " n a m e " : " j u l i e l a m m " , " o r d e r " : 3 7 } , { " c a s t _ i d " : 5 9 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 7 , " n a m e " : " c u l l e n b . m a d d e n " , " o r d e r " : 3 8 } , { " c a s t _ i d " : 6 0 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 9 , " n a m e " : " j o s e p h b r a d y m a d d e n " , " o r d e r " : 3 9 } , { " c a s t _ i d " : 6 1 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 2 , " n a m e " : " f r a n k i e t o r r e s " , " o r d e r " : 4 0 } , { " c a s t _ i d " : 6 2 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " , " g e n d e r " : 1 , " i d " : 1 1 5 8 6 0 0 , " n a m e " : " a u s t i n w i l s o n " , " o r d e r " : 4 1 } , { " c a s t _ i d " : 6 3 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " , " g e n d e r " : 1 , " i d " : 9 8 3 7 0 5 , " n a m e " : " s a r a w i l s o n " , " o r d e r " : 4 2 } , { " c a s t _ i d " : 6 4 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 3 , " n a m e " : " t a m i c a w a s h i n g t o n - m i l l e r " , " o r d e r " : 4 3 } , { " c a s t _ i d " : 6 5 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " , " g e n d e r " : 1 , " i d " : 1 1 4 5 0 9 8 , " n a m e " : " l u c y b r i a n t " , " o r d e r " : 4 4 } , { " c a s t _ i d " : 6 6 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " , " g e n d e r " : 2 , " i d " : 3 3 3 0 5 , " n a m e " : " n a t h a n m e i s t e r " , " o r d e r " : 4 5 } , { " c a s t _ i d " : 6 7 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 4 , " n a m e " : " g e r r y b l a i r " , " o r d e r " : 4 6 } , { " c a s t _ i d " : 6 8 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " , " g e n d e r " : 2 , " i d " : 3 3 3 1 1 , " n a m e " : " m a t t h e w c h a m b e r l a i n " , " o r d e r " : 4 7 } , { " c a s t _ i d " : 6 9 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 5 , " n a m e " : " p a u l y a t e s " , " o r d e r " : 4 8 } , { " c a s t _ i d " : 7 0 , " c h a r a c t e r " : " o p c e n t e r d u t y o f f i c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 6 , " n a m e " : " w r a y w i l s o n " , " o r d e r " : 4 9 } , { " c a s t _ i d " : 7 1 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " , " g e n d e r " : 2 , " i d " : 5 4 4 9 2 , " n a m e " : " j a m e s g a y l y n " , " o r d e r " : 5 0 } , { " c a s t _ i d " : 7 2 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 7 , " n a m e " : " m e l v i n l e n o c l a r k i i i " , " o r d e r " : 5 1 } , { " c a s t _ i d " : 7 3 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 8 , " n a m e " : " c a r v o n f u t r e l l " , " o r d e r " : 5 2 } , { " c a s t _ i d " : 7 4 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 9 , " n a m e " : " b r a n d o n j e l k e s " , " o r d e r " : 5 3 } , { " c a s t _ i d " : 7 5 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 0 , " n a m e " : " m i c a h m o c h " , " o r d e r " : 5 4 } , { " c a s t _ i d " : 7 6 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 1 , " n a m e " : " h a n n i y a h m u h a m m a d " , " o r d e r " : 5 5 } , { " c a s t _ i d " : 7 7 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 2 , " n a m e " : " c h r i s t o p h e r n o l e n " , " o r d e r " : 5 6 } , { " c a s t _ i d " : 7 8 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 3 , " n a m e " : " c h r i s t a o l i v e r " , " o r d e r " : 5 7 } , { " c a s t _ i d " : 7 9 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 4 , " n a m e " : " a p r i l m a r i e t h o m a s " , " o r d e r " : 5 8 } , { " c a s t _ i d " : 8 0 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 5 , " n a m e " : " b r a v i t a a . t h r e a t t " , " o r d e r " : 5 9 } , { " c a s t _ i d " : 8 1 , " c h a r a c t e r " : " m i n i n g c h i e f ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 6 , " n a m e " : " c o l i n b l e a s d a l e " , " o r d e r " : 6 0 } , { " c a s t _ i d " : 8 2 , " c h a r a c t e r " : " v e t e r a n m i n e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " , " g e n d e r " : 0 , " i d " : 1 0 7 9 6 9 , " n a m e " : " m i k e b o d n a r " , " o r d e r " : 6 1 } , { " c a s t _ i d " : 8 3 , " c h a r a c t e r " : " r i c h a r d ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 8 , " n a m e " : " m a t t c l a y t o n " , " o r d e r " : 6 2 } , { " c a s t _ i d " : 8 4 , " c h a r a c t e r " : " n a v \' i ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 7 " , " g e n d e r " : 1 , " i d " : 1 4 7 8 9 8 , " n a m e " : " n i c o l e d i o n n e " , " o r d e r " : 6 3 } , { " c a s t _ i d " : 8 5 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 0 , " n a m e " : " j a m i e h a r r i s o n " , " o r d e r " : 6 4 } , { " c a s t _ i d " : 8 6 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 1 , " n a m e " : " a l l a n h e n r y " , " o r d e r " : 6 5 } , { " c a s t _ i d " : 8 7 , " c h a r a c t e r " : " g r o u n d t e c h n i c i a n ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 3 " , " g e n d e r " : 2 , " i d " : 1 2 0 7 2 8 2 , " n a m e " : " a n t h o n y i n g r u b e r " , " o r d e r " : 6 6 } , { " c a s t _ i d " : 8 8 , " c h a r a c t e r " : " f l i g h t c r e w m e c h a n i c ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 3 , " n a m e " : " a s h l e y j e f f e r y " , " o r d e r " : 6 7 } , { " c a s t _ i d " : 1 4 , " c h a r a c t e r " : " s a m s o n p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 9 " , " g e n d e r " : 0 , " i d " : 9 8 2 1 6 , " n a m e " : " d e a n k n o w s l e y " , " o r d e r " : 6 8 } , { " c a s t _ i d " : 8 9 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 b " , " g e n d e r " : 0 , " i d " : 1 2 0 1 3 9 9 , " n a m e " : " j o s e p h m i k a - h u n t " , " o r d e r " : 6 9 } , { " c a s t _ i d " : 9 0 , " c h a r a c t e r " : " b a n s h e e ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 f " , " g e n d e r " : 0 , " i d " : 2 3 6 6 9 6 , " n a m e " : " t e r r y n o t a r y " , " o r d e r " : 7 0 } , { " c a s t _ i d " : 9 1 , " c h a r a c t e r " : " s 

In [136]:
new_df['tags'][1300]

'new york fashion design melani carmichael suddenli find herself engag to the city\' most elig bachelor. but melanie\' past hold mani secrets, includ jake, the redneck husband she marri in high school, who refus to divorc her. bound and determin to end their contenti relationship onc and for all, melani sneak back home to alabama to confront her past. comedi romanc newyork marriagepropos alabama careerwoman fashiondesign [ { " c a s t _ i d " : 1 , " c h a r a c t e r " : " m e l a n i e \\ " c a r m i c h a e l \\ " s m o o t e r p e r r y " , " c r e d i t _ i d " : " 5 2 f e 4 4 5 3 9 2 5 1 4 1 6 c 7 5 0 3 0 b f d " , " g e n d e r " : 1 , " i d " : 3 6 8 , " n a m e " : " r e e s e w i t h e r s p o o n " , " o r d e r " : 0 } , { " c a s t _ i d " : 2 , " c h a r a c t e r " : " j a k e p e r r y " , " c r e d i t _ i d " : " 5 2 f e 4 4 5 3 9 2 5 1 4 1 6 c 7 5 0 3 0 c 0 1 " , " g e n d e r " : 1 , " i d " : 6 1 6 4 , " n a m e " : " j o s h l u c a s " , " o r d e r " : 1 } , { " c a s t _ i d " : 3 , " c h a r a c t e r " : " a n d r e w h e n n i n g s " , " c r e d i t _ i d " : " 5 2 f e 4 4 5 3 9 2 5 1 4 1 6 c 7 5 0 3 0 c 0 5 " , " g e n d e r " : 2 , " i d " : 1 8 3 5 2 , " n a m e " : " p a t r i c k d e m p s e y " , " o r d e r " : 2 } , { " c a s t _ i d " : 4 , " c h a r a c t e r " : " m a y o r k a t e h e n n i n g s " , " c r e d i t _ i d " : " 5 2 f e 4 4 5 3 9 2 5 1 4 1 6 c 7 5 0 3 0 c 0 9 " , " g e n d e r " : 1 , " i d " : 1 1 8 5 0 , " n a m e " : " c a n d i c e b e r g e n " , " o r d e r " : 3 } , { " c a s t _ i d " : 1 7 , " c h a r a c t e r " : " t a b a t h a w a d m o r e - s m i t h " , " c r e d i t _ i d " : " 5 2 f e 4 4 5 3 9 2 5 1 4 1 6 c 7 5 0 3 0 c 4 f " , " g e n d e r " : 1 , " i d " : 2 5 7 0 2 , " n a m e " : " r h o n a m i t r a " , " o r d e r " : 4 } , { " c a s t _ i d " : 4 3 , " c h a r a c t e r " : " s h e r m a " , " c r e d i t _ i d " : " 5 7 2 9 f 6 5 0 9 2 5 1 4 1 7 0 7 b 0 0 2 4 e 7 " , " g e n d e r " : 1 , " i d " : 2 9 9 3 1 , " n a m e " : " d e b o r a h d u k e " , " o r d e r " : 5 } , { " c a s t _ i d " : 4 4 , " c h a r a c t e r " : " e a r l s m o o t e r " , " c r e d i t _ i d " : " 5 7 8 1 f 8 2 7 c 3 a 3 6 8 5 9 2 2 0 0 6 c 0 5 " , " g e n d e r " : 2 , " i d " : 1 0 4 3 0 , " n a m e " : " f r e d w a r d " , " o r d e r " : 6 } , { " c a s t _ i d " : 4 5 , " c h a r a c t e r " : " p e a r l s m o o t e r " , " c r e d i t _ i d " : " 5 7 8 1 f 8 7 d 9 2 5 1 4 1 7 b 8 e 0 0 4 3 0 6 " , " g e n d e r " : 1 , " i d " : 5 9 6 0 , " n a m e " : " m a r y k a y p l a c e " , " o r d e r " : 7 } , { " c a s t _ i d " : 4 6 , " c h a r a c t e r " : " b a r r y l o w e n s t e i n " , " c r e d i t _ i d " : " 5 7 8 1 f 8 c 6 c 3 a 3 6 8 5 9 2 2 0 0 6 c 2 e " , " g e n d e r " : 2 , " i d " : 6 0 6 3 3 , " n a m e " : " k e v i n s u s s m a n " , " o r d e r " : 8 } , { " c a s t _ i d " : 4 7 , " c h a r a c t e r " : " l u r l y n n " , " c r e d i t _ i d " : " 5 7 8 1 f 9 2 1 9 2 5 1 4 1 7 c c 6 0 0 1 6 c e " , " g e n d e r " : 1 , " i d " : 1 5 0 9 1 , " n a m e " : " m e l a n i e l y n s k e y " , " o r d e r " : 9 } , { " c a s t _ i d " : 4 8 , " c h a r a c t e r " : " b o b b y r a y " , " c r e d i t _ i d " : " 5 7 8 2 0 a 4 1 9 2 5 1 4 1 7 c 4 c 0 0 1 c 3 5 " , " g e n d e r " : 2 , " i d " : 5 8 0 1 9 , " n a m e " : " e t h a n e m b r y " , " o r d e r " : 1 0 } , { " c a s t _ i d " : 4 9 , " c h a r a c t e r " : " s t e l l a k a y " , " c r e d i t _ i d " : " 5 7 8 2 0 a a 7 c 3 a 3 6 8 7 3 e a 0 0 4 a b 5 " , " g e n d e r " : 1 , " i d " : 5 3 7 6 , " n a m e " : " j e a n s m a r t " , " o r d e r " : 1 1 } , { " c a s t _ i d " : 5 0 , " c h a r a c t e r " : " v i r g i e " , " c r e d i t _ i d " : " 5 7 b b 1 b 2 3 c 3 a 3 6 8 6 f a b 0 0 0 6 7 0 " , " g e n d e r " : 1 , " i d " : 1 4 6 0 2 5 , " n a m e " : " s h a r o n b l a c k w o o d " , " o r d e r " : 1 2 } , { " c a s t _ i d " : 5 1 , " c h a r a c t e r " : " y o u n g m e l a n i e s m o o t e r " , " c r e d i t _ i d " : " 5 7 c b a 3 2 d 9 2 5 1 4 1 3 5 1 4 0 0 8 b 6 1 " , " g e n d e r " : 1 , " i d " : 5 0 1 , " n a m e " : " d a k o t a f a n n i n g " , " o r d e r " : 1 3 } , { " c a s t _ i d " : 5 2 , " c h a r a c t e r " : " d e a d s o l d i e r " , " c r e d i t _ i d " : " 5 7 f f a 8 7 b 9 2 5 1 4 1 1 a d 5 0 0 0 3 a 6 " , " g e n d e r " : 2 , " i d " : 1 0 2 4 3 1 2 , " n a m e " : " j o d y t h o m p s o n " , " o r d e r " : 1 4 } , { " c a s t _ i d " : 5 3 , " c h a r a c t e r " : " e r i n v a n d e r b i l t " , " c r e d i t _ i d " : " 5 8 b c 7 5 f f c 3 a 3 6 8 5 1 c d 0 2 4 c 4 6 " , " g e n d e r " : 0 , " i d " : 1 5 0 1 2 , " n a m e " : " k a t h a r i n e t o w n e " , " o r d e r " : 1 5 } ] andytenn'

In [137]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [138]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [139]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [140]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [141]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'],
      shape=(5000,), dtype=object)

In [142]:
['loved','loving','love']
['love','love','love']

['love', 'love', 'love']

In [143]:
ps.stem('dancing')

'danc'

In [144]:
stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d [ { " c a s t _ i d " :  2 4 2 ,  " c h a r a c t e r " :  " J a k e  S u l l y " ,  " c r e d i t _ i d " :  " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " ,  " g e n d e r " :  2 ,  " i d " :  6 5 7 3 1 ,  " n a m e " :  " S a m  W o r t h i n g t o n " ,  " o r d e r " :  0 } ,  { " c a s t _ i d " :  3 ,  " c h a r a c t e r " :  " N e y t i r i " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " ,  " g e n d e r " :  1 ,  " i d " :  8 6 9 1 ,  " n a m e " :  " Z o e  S a l d a n a " ,  " o r d e r " :  1 } ,  { " c a s t _ i d " :  2 5 ,  " c h a r a c t e r " :  " D r .  G r a c e  A u g u s t i n e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " ,  " g e n d e r " :  1 ,  " i d " :  1 0 2 0 5 ,  " n a m e " :  " S i g o u r n e y  W e a v e r " ,  " o r d e r " :  2 } ,  { " c a s t _ i d " :  4 ,  " c h a r a c t e r " :  " C o l .  Q u a r i t c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " ,  " g e n d e r " :  2 ,  " i d " :  3 2 7 4 7 ,  " n a m e " :  " S t e p h e n  L a n g " ,  " o r d e r " :  3 } ,  { " c a s t _ i d " :  5 ,  " c h a r a c t e r " :  " T r u d y  C h a c o n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " ,  " g e n d e r " :  1 ,  " i d " :  1 7 6 4 7 ,  " n a m e " :  " M i c h e l l e  R o d r i g u e z " ,  " o r d e r " :  4 } ,  { " c a s t _ i d " :  8 ,  " c h a r a c t e r " :  " S e l f r i d g e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 7 1 ,  " n a m e " :  " G i o v a n n i  R i b i s i " ,  " o r d e r " :  5 } ,  { " c a s t _ i d " :  7 ,  " c h a r a c t e r " :  " N o r m  S p e l l m a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " ,  " g e n d e r " :  2 ,  " i d " :  5 9 2 3 1 ,  " n a m e " :  " J o e l  D a v i d  M o o r e " ,  " o r d e r " :  6 } ,  { " c a s t _ i d " :  9 ,  " c h a r a c t e r " :  " M o a t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " ,  " g e n d e r " :  1 ,  " i d " :  3 0 4 8 5 ,  " n a m e " :  " C C H  P o u n d e r " ,  " o r d e r " :  7 } ,  { " c a s t _ i d " :  1 1 ,  " c h a r a c t e r " :  " E y t u k a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " ,  " g e n d e r " :  2 ,  " i d " :  1 5 8 5 3 ,  " n a m e " :  " W e s  S t u d i " ,  " o r d e r " :  8 } ,  { " c a s t _ i d " :  1 0 ,  " c h a r a c t e r " :  " T s u \' T e y " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 9 6 4 ,  " n a m e " :  " L a z  A l o n s o " ,  " o r d e r " :  9 } ,  { " c a s t _ i d " :  1 2 ,  " c h a r a c t e r " :  " D r .  M a x  P a t e l " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " ,  " g e n d e r " :  2 ,  " i d " :  9 5 6 9 7 ,  " n a m e " :  " D i l e e p  R a o " ,  " o r d e r " :  1 0 } ,  { " c a s t _ i d " :  1 3 ,  " c h a r a c t e r " :  " L y l e  W a i n f l e e t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 2 1 5 ,  " n a m e " :  " M a t t  G e r a l d " ,  " o r d e r " :  1 1 } ,  { " c a s t _ i d " :  3 2 ,  " c h a r a c t e r " :  " P r i v a t e  F i k e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " ,  " g e n d e r " :  2 ,  " i d " :  1 5 4 1 5 3 ,  " n a m e " :  " S e a n  A n t h o n y  M o r a n " ,  " o r d e r " :  1 2 } ,  { " c a s t _ i d " :  3 3 ,  " c h a r a c t e r " :  " C r y o  V a u l t  M e d  T e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " ,  " g e n d e r " :  2 ,  " i d " :  3 9 7 3 1 2 ,  " n a m e " :  " J a s o n  W h y t e " ,  " o r d e r " :  1 3 } ,  { " c a s t _ i d " :  3 4 ,  " c h a r a c t e r " :  " V e n t u r e  S t a r  C r e w  C h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " ,  " g e n d e r " :  2 ,  " i d " :  4 2 3 1 7 ,  " n a m e " :  " S c o t t  L a w r e n c e " ,  " o r d e r " :  1 4 } ,  { " c a s t _ i d " :  3 5 ,  " c h a r a c t e r " :  " L o c k  U p  T r o o p e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 6 7 3 4 ,  " n a m e " :  " K e l l y  K i l g o u r " ,  " o r d e r " :  1 5 } ,  { " c a s t _ i d " :  3 6 ,  " c h a r a c t e r " :  " S h u t t l e  P i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 2 7 ,  " n a m e " :  " J a m e s  P a t r i c k  P i t t " ,  " o r d e r " :  1 6 } ,  { " c a s t _ i d " :  3 7 ,  " c h a r a c t e r " :  " S h u t t l e  C o - P i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " ,  " g e n d e r " :  0 ,  " i d " :  1 1 8 0 9 3 6 ,  " n a m e " :  " S e a n  P a t r i c k  M u r p h y " ,  " o r d e r " :  1 7 } ,  { " c a s t _ i d " :  3 8 ,  " c h a r a c t e r " :  " S h u t t l e  C r e w  C h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 1 9 5 7 8 ,  " n a m e " :  " P e t e r  D i l l o n " ,  " o r d e r " :  1 8 } ,  { " c a s t _ i d " :  3 9 ,  " c h a r a c t e r " :  " T r a c t o r  O p e r a t o r  /  T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " ,  " g e n d e r " :  0 ,  " i d " :  9 1 4 4 3 ,  " n a m e " :  " K e v i n  D o r m a n " ,  " o r d e r " :  1 9 } ,  { " c a s t _ i d " :  4 0 ,  " c h a r a c t e r " :  " D r a g o n  G u n s h i p  P i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " ,  " g e n d e r " :  2 ,  " i d " :  1 7 3 3 9 1 ,  " n a m e " :  " K e l s o n  H e n d e r s o n " ,  " o r d e r " :  2 0 } ,  { " c a s t _ i d " :  4 1 ,  " c h a r a c t e r " :  " D r a g o n  G u n s h i p  G u n n e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 3 6 ,  " n a m e " :  " D a v i d  V a n  H o r n " ,  " o r d e r " :  2 1 } ,  { " c a s t _ i d " :  4 2 ,  " c h a r a c t e r " :  " D r a g o n  G u n s h i p  N a v i g a t o r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " ,  " g e n d e r " :  0 ,  " i d " :  2 1 5 9 1 3 ,  " n a m e " :  " J a c o b  T o m u r i " ,  " o r d e r " :  2 2 } ,  { " c a s t _ i d " :  4 3 ,  " c h a r a c t e r " :  " S u i t  # 1 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 4 3 2 0 6 ,  " n a m e " :  " M i c h a e l  B l a i n - R o z g a y " ,  " o r d e r " :  2 3 } ,  { " c a s t _ i d " :  4 4 ,  " c h a r a c t e r " :  " S u i t  # 2 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " ,  " g e n d e r " :  2 ,  " i d " :  1 6 9 6 7 6 ,  " n a m e " :  " J o n  C u r r y " ,  " o r d e r " :  2 4 } ,  { " c a s t _ i d " :  4 6 ,  " c h a r a c t e r " :  " A m b i e n t  R o o m  T e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 4 8 6 1 0 ,  " n a m e " :  " L u k e  H a w k e r " ,  " o r d e r " :  2 5 } ,  { " c a s t _ i d " :  4 7 ,  " c h a r a c t e r " :  " A m b i e n t  R o o m  T e c h  /  T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " ,  " g e n d e r " :  0 ,  " i d " :  4 2 2 8 8 ,  " n a m e " :  " W o o d y  S c h u l t z " ,  " o r d e r " :  2 6 } ,  { " c a s t _ i d " :  4 8 ,  " c h a r a c t e r " :  " H o r s e  C l a n  L e a d e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " ,  " g e n d e r " :  2 ,  " i d " :  6 8 2 7 8 ,  " n a m e " :  " P e t e r  M e n s a h " ,  " o r d e r " :  2 7 } ,  { " c a s t _ i d " :  4 9 ,  " c h a r a c t e r " :  " L i n k  R o o m  T e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 7 ,  " n a m e " :  " S o n i a  Y e e " ,  " o r d e r " :  2 8 } ,  { " c a s t _ i d " :  5 0 ,  " c h a r a c t e r " :  " B a s k e t b a l l  A v a t a r  /  T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " ,  " g e n d e r " :  1 ,  " i d " :  1 2 0 7 2 4 8 ,  " n a m e " :  " J a h n e l  C u r f m a n " ,  " o r d e r " :  2 9 } ,  { " c a s t _ i d " :  5 1 ,  " c h a r a c t e r " :  " B a s k e t b a l l  A v a t a r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " ,  " g e n d e r " :  0 ,  " i d " :  8 9 7 1 4 ,  " n a m e " :  " I l r a m  C h o i " ,  " o r d e r " :  3 0 } ,  { " c a s t _ i d " :  5 2 ,  " c h a r a c t e r " :  " N a \' v i  C h i l d " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 9 ,  " n a m e " :  " K y l a  W a r r e n " ,  " o r d e r " :  3 1 } ,  { " c a s t _ i d " :  5 3 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 0 ,  " n a m e " :  " L i s a  R o u m a i n " ,  " o r d e r " :  3 2 } ,  { " c a s t _ i d " :  5 4 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " ,  " g e n d e r " :  1 ,  " i d " :  8 3 1 0 5 ,  " n a m e " :  " D e b r a  W i l s o n " ,  " o r d e r " :  3 3 } ,  { " c a s t _ i d " :  5 7 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 3 ,  " n a m e " :  " C h r i s  M a l a " ,  " o r d e r " :  3 4 } ,  { " c a s t _ i d " :  5 5 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 1 ,  " n a m e " :  " T a y l o r  K i b b y " ,  " o r d e r " :  3 5 } ,  { " c a s t _ i d " :  5 6 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 2 ,  " n a m e " :  " J o d i e  L a n d a u " ,  " o r d e r " :  3 6 } ,  { " c a s t _ i d " :  5 8 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 4 ,  " n a m e " :  " J u l i e  L a m m " ,  " o r d e r " :  3 7 } ,  { " c a s t _ i d " :  5 9 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 7 ,  " n a m e " :  " C u l l e n  B .  M a d d e n " ,  " o r d e r " :  3 8 } ,  { " c a s t _ i d " :  6 0 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 9 ,  " n a m e " :  " J o s e p h  B r a d y  M a d d e n " ,  " o r d e r " :  3 9 } ,  { " c a s t _ i d " :  6 1 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 2 ,  " n a m e " :  " F r a n k i e  T o r r e s " ,  " o r d e r " :  4 0 } ,  { " c a s t _ i d " :  6 2 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " ,  " g e n d e r " :  1 ,  " i d " :  1 1 5 8 6 0 0 ,  " n a m e " :  " A u s t i n  W i l s o n " ,  " o r d e r " :  4 1 } ,  { " c a s t _ i d " :  6 3 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " ,  " g e n d e r " :  1 ,  " i d " :  9 8 3 7 0 5 ,  " n a m e " :  " S a r a  W i l s o n " ,  " o r d e r " :  4 2 } ,  { " c a s t _ i d " :  6 4 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 3 ,  " n a m e " :  " T a m i c a  W a s h i n g t o n - M i l l e r " ,  " o r d e r " :  4 3 } ,  { " c a s t _ i d " :  6 5 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " ,  " g e n d e r " :  1 ,  " i d " :  1 1 4 5 0 9 8 ,  " n a m e " :  " L u c y  B r i a n t " ,  " o r d e r " :  4 4 } ,  { " c a s t _ i d " :  6 6 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 0 5 ,  " n a m e " :  " N a t h a n  M e i s t e r " ,  " o r d e r " :  4 5 } ,  { " c a s t _ i d " :  6 7 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 4 ,  " n a m e " :  " G e r r y  B l a i r " ,  " o r d e r " :  4 6 } ,  { " c a s t _ i d " :  6 8 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 1 1 ,  " n a m e " :  " M a t t h e w  C h a m b e r l a i n " ,  " o r d e r " :  4 7 } ,  { " c a s t _ i d " :  6 9 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 5 ,  " n a m e " :  " P a u l  Y a t e s " ,  " o r d e r " :  4 8 } ,  { " c a s t _ i d " :  7 0 ,  " c h a r a c t e r " :  " O p  C e n t e r  D u t y  O f f i c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 6 ,  " n a m e " :  " W r a y  W i l s o n " ,  " o r d e r " :  4 9 } ,  { " c a s t _ i d " :  7 1 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " ,  " g e n d e r " :  2 ,  " i d " :  5 4 4 9 2 ,  " n a m e " :  " J a m e s  G a y l y n " ,  " o r d e r " :  5 0 } ,  { " c a s t _ i d " :  7 2 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 7 ,  " n a m e " :  " M e l v i n  L e n o  C l a r k  I I I " ,  " o r d e r " :  5 1 } ,  { " c a s t _ i d " :  7 3 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 8 ,  " n a m e " :  " C a r v o n  F u t r e l l " ,  " o r d e r " :  5 2 } ,  { " c a s t _ i d " :  7 4 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 9 ,  " n a m e " :  " B r a n d o n  J e l k e s " ,  " o r d e r " :  5 3 } ,  { " c a s t _ i d " :  7 5 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 0 ,  " n a m e " :  " M i c a h  M o c h " ,  " o r d e r " :  5 4 } ,  { " c a s t _ i d " :  7 6 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 1 ,  " n a m e " :  " H a n n i y a h  M u h a m m a d " ,  " o r d e r " :  5 5 } ,  { " c a s t _ i d " :  7 7 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 2 ,  " n a m e " :  " C h r i s t o p h e r  N o l e n " ,  " o r d e r " :  5 6 } ,  { " c a s t _ i d " :  7 8 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 3 ,  " n a m e " :  " C h r i s t a  O l i v e r " ,  " o r d e r " :  5 7 } ,  { " c a s t _ i d " :  7 9 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 4 ,  " n a m e " :  " A p r i l  M a r i e  T h o m a s " ,  " o r d e r " :  5 8 } ,  { " c a s t _ i d " :  8 0 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 5 ,  " n a m e " :  " B r a v i t a  A .  T h r e a t t " ,  " o r d e r " :  5 9 } ,  { " c a s t _ i d " :  8 1 ,  " c h a r a c t e r " :  " M i n i n g  C h i e f  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 6 ,  " n a m e " :  " C o l i n  B l e a s d a l e " ,  " o r d e r " :  6 0 } ,  { " c a s t _ i d " :  8 2 ,  " c h a r a c t e r " :  " V e t e r a n  M i n e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 7 9 6 9 ,  " n a m e " :  " M i k e  B o d n a r " ,  " o r d e r " :  6 1 } ,  { " c a s t _ i d " :  8 3 ,  " c h a r a c t e r " :  " R i c h a r d  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 8 ,  " n a m e " :  " M a t t  C l a y t o n " ,  " o r d e r " :  6 2 } ,  { " c a s t _ i d " :  8 4 ,  " c h a r a c t e r " :  " N a v \' i  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 7 " ,  " g e n d e r " :  1 ,  " i d " :  1 4 7 8 9 8 ,  " n a m e " :  " N i c o l e  D i o n n e " ,  " o r d e r " :  6 3 } ,  { " c a s t _ i d " :  8 5 ,  " c h a r a c t e r " :  " T r o o p e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 0 ,  " n a m e " :  " J a m i e  H a r r i s o n " ,  " o r d e r " :  6 4 } ,  { " c a s t _ i d " :  8 6 ,  " c h a r a c t e r " :  " T r o o p e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 1 ,  " n a m e " :  " A l l a n  H e n r y " ,  " o r d e r " :  6 5 } ,  { " c a s t _ i d " :  8 7 ,  " c h a r a c t e r " :  " G r o u n d  T e c h n i c i a n  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 2 0 7 2 8 2 ,  " n a m e " :  " A n t h o n y  I n g r u b e r " ,  " o r d e r " :  6 6 } ,  { " c a s t _ i d " :  8 8 ,  " c h a r a c t e r " :  " F l i g h t  C r e w  M e c h a n i c  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 3 ,  " n a m e " :  " A s h l e y  J e f f e r y " ,  " o r d e r " :  6 7 } ,  { " c a s t _ i d " :  1 4 ,  " c h a r a c t e r " :  " S a m s o n  P i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 9 " ,  " g e n d e r " :  0 ,  " i d " :  9 8 2 1 6 ,  " n a m e " :  " D e a n  K n o w s l e y " ,  " o r d e r " :  6 8 } ,  { " c a s t _ i d " :  8 9 ,  " c h a r a c t e r " :  " T r o o p e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 1 3 9 9 ,  " n a m e " :  " J o s e p h  M i k a - H u n t " ,  " o r d e r " :  6 9 } ,  { " c a s t _ i d " :  9 0 ,  " c h a r a c t e r " :  " B a n s h e e  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 f " ,  " g e n d e r " :  0 ,  " i d " :  2 3 6 6 9 6 ,  " n a m e " :  " T e r r y  N o t a r y " ,  " o r d e r " :  7 0 } ,  { " c a s t _ i d " :  9 1 ,  " c h a r a c t e r " :  " S o l d i e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 4 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 7 ,  " n a m e " :  " K a i  P a n t a n o " ,  " o r d e r " :  7 1 } ,  { " c a s t _ i d " :  9 2 ,  " c h a r a c t e r " :  " B l a s t  T e c h n i c i a n  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 4 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 8 ,  " n a m e " :  " L o g a n  P i t h y o u " ,  " o r d e r " :  7 2 } ,  { " c a s t _ i d " :  9 3 ,  " c h a r a c t e r " :  " V i n d u m  R a a h  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 4 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 9 ,  " n a m e " :  " S t u a r t  P o l l o c k " ,  " o r d e r " :  7 3 } ,  { " c a s t _ i d " :  9 4 ,  " c h a r a c t e r " :  " H e r o  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 4 f " ,  " g e n d e r " :  0 ,  " i d " :  5 8 4 8 6 8 ,  " n a m e " :  " R a j a " ,  " o r d e r " :  7 4 } ,  { " c a s t _ i d " :  9 5 ,  " c h a r a c t e r " :  " O p s  C e n t r e w o r k e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 5 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 9 0 ,  " n a m e " :  " G a r e t h  R u c k " ,  " o r d e r " :  7 5 } ,  { " c a s t _ i d " :  9 6 ,  " c h a r a c t e r " :  " E n g i n e e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 5 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 0 6 2 4 6 3 ,  " n a m e " :  " R h i a n  S h e e h a n " ,  " o r d e r " :  7 6 } ,  { " c a s t _ i d " :  9 7 ,  " c h a r a c t e r " :  " C o l .  Q u a r i t c h \' s  M e c h  S u i t  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 5 b " ,  " g e n d e r " :  0 ,  " i d " :  6 0 6 5 6 ,  " n a m e " :  " T .  J .  S t o r m " ,  " o r d e r " :  7 7 } ,  { " c a s t _ i d " :  9 8 ,  " c h a r a c t e r " :  " F e m a l e  M a r i n e  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 5 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 9 1 ,  " n a m e " :  " J o d i e  T a y l o r " ,  " o r d e r " :  7 8 } ,  { " c a s t _ i d " :  9 9 ,  " c h a r a c t e r " :  " I k r a n  C l a n  L e a d e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 6 3 " ,  " g e n d e r " :  1 ,  " i d " :  1 1 8 6 0 2 7 ,  " n a m e " :  " A l i c i a  V e l a - B a i l e y " ,  " o r d e r " :  7 9 } ,  { " c a s t _ i d " :  1 0 0 ,  " c h a r a c t e r " :  " G e o l o g i s t  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 6 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 9 2 ,  " n a m e " :  " R i c h a r d  W h i t e s i d e " ,  " o r d e r " :  8 0 } ,  { " c a s t _ i d " :  1 0 1 ,  " c h a r a c t e r " :  " N a \' v i  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 6 b " ,  " g e n d e r " :  0 ,  " i d " :  1 0 3 2 5 9 ,  " n a m e " :  " N i k i e  Z a m b o " ,  " o r d e r " :  8 1 } ,  { " c a s t _ i d " :  1 0 2 ,  " c h a r a c t e r " :  " A m b i e n t  R o o m  T e c h  /  T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 6 f " ,  " g e n d e r " :  1 ,  " i d " :  4 2 2 8 6 ,  " n a m e " :  " J u l e n e  R e n e e " ,  " o r d e r " :  8 2 } ] JamesCameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d [ { " c a s t _ i d " : 2 4 2 , " c h a r a c t e r " : " j a k e s u l l y " , " c r e d i t _ i d " : " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " , " g e n d e r " : 2 , " i d " : 6 5 7 3 1 , " n a m e " : " s a m w o r t h i n g t o n " , " o r d e r " : 0 } , { " c a s t _ i d " : 3 , " c h a r a c t e r " : " n e y t i r i " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " , " g e n d e r " : 1 , " i d " : 8 6 9 1 , " n a m e " : " z o e s a l d a n a " , " o r d e r " : 1 } , { " c a s t _ i d " : 2 5 , " c h a r a c t e r " : " d r . g r a c e a u g u s t i n e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " , " g e n d e r " : 1 , " i d " : 1 0 2 0 5 , " n a m e " : " s i g o u r n e y w e a v e r " , " o r d e r " : 2 } , { " c a s t _ i d " : 4 , " c h a r a c t e r " : " c o l . q u a r i t c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " , " g e n d e r " : 2 , " i d " : 3 2 7 4 7 , " n a m e " : " s t e p h e n l a n g " , " o r d e r " : 3 } , { " c a s t _ i d " : 5 , " c h a r a c t e r " : " t r u d y c h a c o n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " , " g e n d e r " : 1 , " i d " : 1 7 6 4 7 , " n a m e " : " m i c h e l l e r o d r i g u e z " , " o r d e r " : 4 } , { " c a s t _ i d " : 8 , " c h a r a c t e r " : " s e l f r i d g e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " , " g e n d e r " : 2 , " i d " : 1 7 7 1 , " n a m e " : " g i o v a n n i r i b i s i " , " o r d e r " : 5 } , { " c a s t _ i d " : 7 , " c h a r a c t e r " : " n o r m s p e l l m a n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " , " g e n d e r " : 2 , " i d " : 5 9 2 3 1 , " n a m e " : " j o e l d a v i d m o o r e " , " o r d e r " : 6 } , { " c a s t _ i d " : 9 , " c h a r a c t e r " : " m o a t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " , " g e n d e r " : 1 , " i d " : 3 0 4 8 5 , " n a m e " : " c c h p o u n d e r " , " o r d e r " : 7 } , { " c a s t _ i d " : 1 1 , " c h a r a c t e r " : " e y t u k a n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " , " g e n d e r " : 2 , " i d " : 1 5 8 5 3 , " n a m e " : " w e s s t u d i " , " o r d e r " : 8 } , { " c a s t _ i d " : 1 0 , " c h a r a c t e r " : " t s u \' t e y " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " , " g e n d e r " : 2 , " i d " : 1 0 9 6 4 , " n a m e " : " l a z a l o n s o " , " o r d e r " : 9 } , { " c a s t _ i d " : 1 2 , " c h a r a c t e r " : " d r . m a x p a t e l " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " , " g e n d e r " : 2 , " i d " : 9 5 6 9 7 , " n a m e " : " d i l e e p r a o " , " o r d e r " : 1 0 } , { " c a s t _ i d " : 1 3 , " c h a r a c t e r " : " l y l e w a i n f l e e t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " , " g e n d e r " : 2 , " i d " : 9 8 2 1 5 , " n a m e " : " m a t t g e r a l d " , " o r d e r " : 1 1 } , { " c a s t _ i d " : 3 2 , " c h a r a c t e r " : " p r i v a t e f i k e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " , " g e n d e r " : 2 , " i d " : 1 5 4 1 5 3 , " n a m e " : " s e a n a n t h o n y m o r a n " , " o r d e r " : 1 2 } , { " c a s t _ i d " : 3 3 , " c h a r a c t e r " : " c r y o v a u l t m e d t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " , " g e n d e r " : 2 , " i d " : 3 9 7 3 1 2 , " n a m e " : " j a s o n w h y t e " , " o r d e r " : 1 3 } , { " c a s t _ i d " : 3 4 , " c h a r a c t e r " : " v e n t u r e s t a r c r e w c h i e f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " , " g e n d e r " : 2 , " i d " : 4 2 3 1 7 , " n a m e " : " s c o t t l a w r e n c e " , " o r d e r " : 1 4 } , { " c a s t _ i d " : 3 5 , " c h a r a c t e r " : " l o c k u p t r o o p e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " , " g e n d e r " : 2 , " i d " : 9 8 6 7 3 4 , " n a m e " : " k e l l y k i l g o u r " , " o r d e r " : 1 5 } , { " c a s t _ i d " : 3 6 , " c h a r a c t e r " : " s h u t t l e p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 2 7 , " n a m e " : " j a m e s p a t r i c k p i t t " , " o r d e r " : 1 6 } , { " c a s t _ i d " : 3 7 , " c h a r a c t e r " : " s h u t t l e c o - p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " , " g e n d e r " : 0 , " i d " : 1 1 8 0 9 3 6 , " n a m e " : " s e a n p a t r i c k m u r p h y " , " o r d e r " : 1 7 } , { " c a s t _ i d " : 3 8 , " c h a r a c t e r " : " s h u t t l e c r e w c h i e f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " , " g e n d e r " : 2 , " i d " : 1 0 1 9 5 7 8 , " n a m e " : " p e t e r d i l l o n " , " o r d e r " : 1 8 } , { " c a s t _ i d " : 3 9 , " c h a r a c t e r " : " t r a c t o r o p e r a t o r / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " , " g e n d e r " : 0 , " i d " : 9 1 4 4 3 , " n a m e " : " k e v i n d o r m a n " , " o r d e r " : 1 9 } , { " c a s t _ i d " : 4 0 , " c h a r a c t e r " : " d r a g o n g u n s h i p p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " , " g e n d e r " : 2 , " i d " : 1 7 3 3 9 1 , " n a m e " : " k e l s o n h e n d e r s o n " , " o r d e r " : 2 0 } , { " c a s t _ i d " : 4 1 , " c h a r a c t e r " : " d r a g o n g u n s h i p g u n n e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 3 6 , " n a m e " : " d a v i d v a n h o r n " , " o r d e r " : 2 1 } , { " c a s t _ i d " : 4 2 , " c h a r a c t e r " : " d r a g o n g u n s h i p n a v i g a t o r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " , " g e n d e r " : 0 , " i d " : 2 1 5 9 1 3 , " n a m e " : " j a c o b t o m u r i " , " o r d e r " : 2 2 } , { " c a s t _ i d " : 4 3 , " c h a r a c t e r " : " s u i t # 1 " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " , " g e n d e r " : 0 , " i d " : 1 4 3 2 0 6 , " n a m e " : " m i c h a e l b l a i n - r o z g a y " , " o r d e r " : 2 3 } , { " c a s t _ i d " : 4 4 , " c h a r a c t e r " : " s u i t # 2 " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " , " g e n d e r " : 2 , " i d " : 1 6 9 6 7 6 , " n a m e " : " j o n c u r r y " , " o r d e r " : 2 4 } , { " c a s t _ i d " : 4 6 , " c h a r a c t e r " : " a m b i e n t r o o m t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " , " g e n d e r " : 0 , " i d " : 1 0 4 8 6 1 0 , " n a m e " : " l u k e h a w k e r " , " o r d e r " : 2 5 } , { " c a s t _ i d " : 4 7 , " c h a r a c t e r " : " a m b i e n t r o o m t e c h / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " , " g e n d e r " : 0 , " i d " : 4 2 2 8 8 , " n a m e " : " w o o d y s c h u l t z " , " o r d e r " : 2 6 } , { " c a s t _ i d " : 4 8 , " c h a r a c t e r " : " h o r s e c l a n l e a d e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " , " g e n d e r " : 2 , " i d " : 6 8 2 7 8 , " n a m e " : " p e t e r m e n s a h " , " o r d e r " : 2 7 } , { " c a s t _ i d " : 4 9 , " c h a r a c t e r " : " l i n k r o o m t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 4 7 , " n a m e " : " s o n i a y e e " , " o r d e r " : 2 8 } , { " c a s t _ i d " : 5 0 , " c h a r a c t e r " : " b a s k e t b a l l a v a t a r / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " , " g e n d e r " : 1 , " i d " : 1 2 0 7 2 4 8 , " n a m e " : " j a h n e l c u r f m a n " , " o r d e r " : 2 9 } , { " c a s t _ i d " : 5 1 , " c h a r a c t e r " : " b a s k e t b a l l a v a t a r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " , " g e n d e r " : 0 , " i d " : 8 9 7 1 4 , " n a m e " : " i l r a m c h o i " , " o r d e r " : 3 0 } , { " c a s t _ i d " : 5 2 , " c h a r a c t e r " : " n a \' v i c h i l d " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 4 9 , " n a m e " : " k y l a w a r r e n " , " o r d e r " : 3 1 } , { " c a s t _ i d " : 5 3 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 0 , " n a m e " : " l i s a r o u m a i n " , " o r d e r " : 3 2 } , { " c a s t _ i d " : 5 4 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " , " g e n d e r " : 1 , " i d " : 8 3 1 0 5 , " n a m e " : " d e b r a w i l s o n " , " o r d e r " : 3 3 } , { " c a s t _ i d " : 5 7 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 3 , " n a m e " : " c h r i s m a l a " , " o r d e r " : 3 4 } , { " c a s t _ i d " : 5 5 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 1 , " n a m e " : " t a y l o r k i b b y " , " o r d e r " : 3 5 } , { " c a s t _ i d " : 5 6 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 2 , " n a m e " : " j o d i e l a n d a u " , " o r d e r " : 3 6 } , { " c a s t _ i d " : 5 8 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 4 , " n a m e " : " j u l i e l a m m " , " o r d e r " : 3 7 } , { " c a s t _ i d " : 5 9 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 7 , " n a m e " : " c u l l e n b . m a d d e n " , " o r d e r " : 3 8 } , { " c a s t _ i d " : 6 0 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 9 , " n a m e " : " j o s e p h b r a d y m a d d e n " , " o r d e r " : 3 9 } , { " c a s t _ i d " : 6 1 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 2 , " n a m e " : " f r a n k i e t o r r e s " , " o r d e r " : 4 0 } , { " c a s t _ i d " : 6 2 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " , " g e n d e r " : 1 , " i d " : 1 1 5 8 6 0 0 , " n a m e " : " a u s t i n w i l s o n " , " o r d e r " : 4 1 } , { " c a s t _ i d " : 6 3 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " , " g e n d e r " : 1 , " i d " : 9 8 3 7 0 5 , " n a m e " : " s a r a w i l s o n " , " o r d e r " : 4 2 } , { " c a s t _ i d " : 6 4 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 3 , " n a m e " : " t a m i c a w a s h i n g t o n - m i l l e r " , " o r d e r " : 4 3 } , { " c a s t _ i d " : 6 5 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " , " g e n d e r " : 1 , " i d " : 1 1 4 5 0 9 8 , " n a m e " : " l u c y b r i a n t " , " o r d e r " : 4 4 } , { " c a s t _ i d " : 6 6 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " , " g e n d e r " : 2 , " i d " : 3 3 3 0 5 , " n a m e " : " n a t h a n m e i s t e r " , " o r d e r " : 4 5 } , { " c a s t _ i d " : 6 7 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 4 , " n a m e " : " g e r r y b l a i r " , " o r d e r " : 4 6 } , { " c a s t _ i d " : 6 8 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " , " g e n d e r " : 2 , " i d " : 3 3 3 1 1 , " n a m e " : " m a t t h e w c h a m b e r l a i n " , " o r d e r " : 4 7 } , { " c a s t _ i d " : 6 9 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 5 , " n a m e " : " p a u l y a t e s " , " o r d e r " : 4 8 } , { " c a s t _ i d " : 7 0 , " c h a r a c t e r " : " o p c e n t e r d u t y o f f i c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 6 , " n a m e " : " w r a y w i l s o n " , " o r d e r " : 4 9 } , { " c a s t _ i d " : 7 1 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " , " g e n d e r " : 2 , " i d " : 5 4 4 9 2 , " n a m e " : " j a m e s g a y l y n " , " o r d e r " : 5 0 } , { " c a s t _ i d " : 7 2 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 7 , " n a m e " : " m e l v i n l e n o c l a r k i i i " , " o r d e r " : 5 1 } , { " c a s t _ i d " : 7 3 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 8 , " n a m e " : " c a r v o n f u t r e l l " , " o r d e r " : 5 2 } , { " c a s t _ i d " : 7 4 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 9 , " n a m e " : " b r a n d o n j e l k e s " , " o r d e r " : 5 3 } , { " c a s t _ i d " : 7 5 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 0 , " n a m e " : " m i c a h m o c h " , " o r d e r " : 5 4 } , { " c a s t _ i d " : 7 6 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 1 , " n a m e " : " h a n n i y a h m u h a m m a d " , " o r d e r " : 5 5 } , { " c a s t _ i d " : 7 7 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 2 , " n a m e " : " c h r i s t o p h e r n o l e n " , " o r d e r " : 5 6 } , { " c a s t _ i d " : 7 8 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 3 , " n a m e " : " c h r i s t a o l i v e r " , " o r d e r " : 5 7 } , { " c a s t _ i d " : 7 9 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 4 , " n a m e " : " a p r i l m a r i e t h o m a s " , " o r d e r " : 5 8 } , { " c a s t _ i d " : 8 0 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 5 , " n a m e " : " b r a v i t a a . t h r e a t t " , " o r d e r " : 5 9 } , { " c a s t _ i d " : 8 1 , " c h a r a c t e r " : " m i n i n g c h i e f ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 6 , " n a m e " : " c o l i n b l e a s d a l e " , " o r d e r " : 6 0 } , { " c a s t _ i d " : 8 2 , " c h a r a c t e r " : " v e t e r a n m i n e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " , " g e n d e r " : 0 , " i d " : 1 0 7 9 6 9 , " n a m e " : " m i k e b o d n a r " , " o r d e r " : 6 1 } , { " c a s t _ i d " : 8 3 , " c h a r a c t e r " : " r i c h a r d ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 8 , " n a m e " : " m a t t c l a y t o n " , " o r d e r " : 6 2 } , { " c a s t _ i d " : 8 4 , " c h a r a c t e r " : " n a v \' i ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 7 " , " g e n d e r " : 1 , " i d " : 1 4 7 8 9 8 , " n a m e " : " n i c o l e d i o n n e " , " o r d e r " : 6 3 } , { " c a s t _ i d " : 8 5 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 0 , " n a m e " : " j a m i e h a r r i s o n " , " o r d e r " : 6 4 } , { " c a s t _ i d " : 8 6 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 1 , " n a m e " : " a l l a n h e n r y " , " o r d e r " : 6 5 } , { " c a s t _ i d " : 8 7 , " c h a r a c t e r " : " g r o u n d t e c h n i c i a n ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 3 " , " g e n d e r " : 2 , " i d " : 1 2 0 7 2 8 2 , " n a m e " : " a n t h o n y i n g r u b e r " , " o r d e r " : 6 6 } , { " c a s t _ i d " : 8 8 , " c h a r a c t e r " : " f l i g h t c r e w m e c h a n i c ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 3 , " n a m e " : " a s h l e y j e f f e r y " , " o r d e r " : 6 7 } , { " c a s t _ i d " : 1 4 , " c h a r a c t e r " : " s a m s o n p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 9 " , " g e n d e r " : 0 , " i d " : 9 8 2 1 6 , " n a m e " : " d e a n k n o w s l e y " , " o r d e r " : 6 8 } , { " c a s t _ i d " : 8 9 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 b " , " g e n d e r " : 0 , " i d " : 1 2 0 1 3 9 9 , " n a m e " : " j o s e p h m i k a - h u n t " , " o r d e r " : 6 9 } , { " c a s t _ i d " : 9 0 , " c h a r a c t e r " : " b a n s h e e ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 f " , " g e n d e r " : 0 , " i d " : 2 3 6 6 9 6 , " n a m e " : " t e r r y n o t a r y " , " o r d e r " : 7 0 } , { " c a s t _ i d " : 9 1 , " c h a r a c t e r " : " s 

In [145]:
from sklearn.metrics.pairwise import cosine_similarity

In [146]:
similarity = cosine_similarity(vectors)

In [147]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1214, np.float64(0.2849014411490948)),
 (539, np.float64(0.2694079530401624)),
 (3728, np.float64(0.2676516895156553)),
 (507, np.float64(0.2649064714130087)),
 (582, np.float64(0.25182770057259657))]

In [148]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [149]:
recommend('Avatar')

Aliens vs Predator: Requiem
Titan A.E.
Falcon Rising
Independence Day
Battle: Los Angeles

In [150]:
new_df.iloc[1216].title

'Autumn in New York'

In [151]:
import pickle

In [152]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [153]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], shape=(4806,), dtype=object)

In [156]:


pickle.dump(new_df.to_dict(), open('movie_dict.pkl', 'wb'))

In [157]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))